export const wrapper: string;
export const fixedDiv: string;
export const logo: string;
export const title: string;
export const container: string;
export const flower: string;
export const hamburger: string;
export const menu: string;
export const menuShow: string;
